# Generated by Django 3.2.16 on 2022-10-10 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmapitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
