# Generated by Django 3.2.16 on 2022-12-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_roadmapitem_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapitem',
            name='description',
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='file',
            field=models.FileField(default=None, upload_to='roadmap_items/'),
            preserve_default=False,
        ),
    ]
