# Generated by Django 3.2.16 on 2022-12-22 18:24

from django.db import migrations, models
import python_web_developer_roadmap.roadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_auto_20221222_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='file',
            field=models.FileField(upload_to=python_web_developer_roadmap.roadmap.models.get_upload_path),
        ),
    ]
