# Generated by Django 3.2.16 on 2023-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_alter_roadmapitem_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmapitem',
            options={'ordering': ('name',)},
        ),
    ]
